services:
  - type: web
    name: jobfit
    runtime: python
    buildCommand: pip install --extra-index-url https://download.pytorch.org/whl/cpu -r requirements.txt
    startCommand: uvicorn webapp.app.main:app --host 0.0.0.0 --port $PORT
