services:
  - type: web
    name: jobfit
    runtime: python
    pythonVersion: 3.12.7
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn webapp.app.main:app --host 0.0.0.0 --port $PORT
